spring.application.name=AktanOOPProject


spring.datasource.username=ort_sgru_user
spring.datasource.password=gujTH8RGhRZ2DYTMvTK89z1t3tHLHWPE
spring.datasource.url=jdbc:postgresql://dpg-d269c03e5dus73dca9fg-a.oregon-postgres.render.com:5432/ort_sgru?sslmode=require

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false


# Mail settings
spring.mail.username=bapaevmyrza.work@gmail.com
spring.mail.password=cmqx jnzq cikw jaql


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp

# File upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
